export default () => {
  return [
    {
      'id':'1',
      'show':'1',
      'headline':'Narcissus',
      'textShort':'Filmen om Narcissus handlar om förnekelse och om sitt eget ansvar för det egna livet. ',
      'textLong':'<span class="CapUp">Historien om  Narcissus<span> <span class="CapDown">är gott och väl 2500 år gammal och tillhör den grekiska mytologin.<BR><BR>Handlingen kretsar kring en man som blev dömd att förälska sig i egen spegelbild, vilket gjorde att han inte kunde slita blicken från sitt ansikte, vilket i sin tur slutade med att han tynade bort. <BR><BR>I min uppdaterade version bär Narcissus på alla de drag en stark självälskande person har. Hans självcentrering har gjort att han stötts bort av hans vänner. Som den narcissistiska person han är, förnekar han sitt eget ansvar och skyller på alla andra. Han har satt ett ultimatum till sina vänner - om de inte dyker upp så kommer han att ta sitt liv. Självklart så tror han att de ska dyka upp och rädda honom och därmed kommer de att bekräfta Narcissus tro att de älskar honom mer än livet.<BR><BR>Den enda som dyker upp är Broder - spegelbilden - den enda som säger sanningen till Narcissus. <BR><BR>Filmen tog två dagar att filma med en RED-kamera. Platsen är en solig och lummig äng vid Sjöändan utanför Norrtälje.<BR><BR>Huvudrollsinnehavaren <a href="http://www.pontusolgrim.se">Pontus Olgrim<a> fick pris för bästa manliga huvudroll i Indie Fest 2012.</span>',
      'textPin':'Filmen om Narcissus handlar om förnekelse och om sitt eget ansvar för det egna livet. ',
      'caseInputDate':'2015-02-23',
      'showArt':'0',
      'quote':'Steffo är artistiskt begåvad med stor fantasi parat med en stark förmåga till avslut. Han är stark i hela produktionskedjan - id\u00e9, manusskrivande, produktion, fotoregi och postproduktion.',
      'quoteName':'Pontus Olgrim<BR>Producent och skådespelare','type':'Kortfilm, 11min',
      'colorSpace':'1',
      'employer':'1',
      'imgCollage':'9',
      'imgCollageSetup':'1,13,5,3',
      'tools':'15,12',
      'tasks':'1,2,6,24,37',
      'format':'RED',
      'year':'2010',
      'link':'http:241production.com',
      'linkName':'241production',
      'imgThumb':'https://raw.githubusercontent.com/steffodimfelt/steffodimfelt.github.io/master/static/img/cases/film/2x1_narcissus_01.jpg'
    },
    {
      'id':'2',
      'show':'1',
      'headline':'Värderingsmannen',
      'textShort':'Värderingsmannen handlar om en man som värderar människors hem. Han har blivit cynisk i sitt arbete och anser att alla människor är lika.',
      'textLong':'<span class=\'CapUp\'>Min senaste film \'Värderingsmannen\'<span> <span class="CapDown">har legat i byrålådan i nio år. Jag kan så här i efterhand säga att jag är glad över att den inte gjordes då utan nu - den behövde ett speciellt format och språk som den inte hade från början. <BR><BR>Värderingsmannen handlar om en man som värderar människors hem. Han har blivit cynisk i sitt arbete och anser att alla människor är lika. Dock får han insikt om vi alla även har något som gör oss till individer. <BR><BR>Filmen tog två och en halv dag att filma. Det var bara jag och skådespelaren på plats. Jag satte ljuset och filmade. Regisserade gjorde vi tillsammans. Merparten av klipparbete gjorde jag men vi har gått igenom klippningen tillsammans. Hittills har det blivit sju korrigeringar. Förutom att sätta allt till svartvitt har jag även gjort mindre VFX-arbeten. <BR><BR>Formspråket kommer från den franska vågens filmer från 60-talet. Allt inspelningsljud är borttaget och ersatt med foley-ljud, som jag jag då själv har gjort merparten av. (Det enda ljudet jag inte gjorde själv var ett fotoblixtljud från en gammal lampblixt.)<BR><BR>Jag är riktigt nöjd med resultatet och särskilt under den korta tid den är producerad. Kostnaden är, förutom arbetstiden, inte mer än max 300kr.<BR><BR>Värderingsmannen spelas av den alltid lika fantastiske Anders Menzinsky.</span>',
      'textPin':'Värderingsmannen handlar om en man som värderar människors hem.',
      'caseInputDate':'2015-06-23',
      'showArt':'1',
      'quote':'Steffo är en seriös och kompetent medarbetare. Hans öga för noggrannhet och detaljer gör att resultat alltid blir förstklassigt. Hans id\u00e9rikedom och påhittighet gör att arbetet alltid känns glädjefyllt och spännande!',
      'quoteName':'Anders Menzinsky<BR>Skådespelare',
      'type':'Kortfilm, 10min',
      'colorSpace':'3',
      'employer':'1',
      'imgCollage':'7',
      'imgCollageSetup':'12,9,10,11',
      'tools':'1,3,12,5,13,15',
      'tasks':'28,1,2,5,11,12,16,22,23,24,34,4, 35,36',
      'format':'MPEG-4H.264',
      'year':'2015',
      'link':null,
      'linkName':null,
      'imgThumb':'https://raw.githubusercontent.com/steffodimfelt/steffodimfelt.github.io/master/static/img/cases/film/2x1-varderingsmannen-01.jpg'
    },
    {
      'id':'3',
      'show':'1',
      'headline':'Amalia',
      'textShort':'Filmen om Amalia baseras på en sann historia om Amalia Meuller från Halmstad som efter att ha fått tre stycken friarbrev, lät sin bästa väninna välja friare.',
      'textLong':'<span class=\'CapUp\'>Filmen om Amalia<span> <span class="CapDown">baseras på en sann historia om Amalia Meuller från Halmstad som efter att ha fått tre stycken friarbrev, lät sin bästa väninna välja friare. Amalia gifte sig med en av friarna, Carl-Magnus Larsson. <BR><BR>Min bror producerade filmen och frågade mig i fall jag var intresserad av att skriva manuset och självklart ville jag det. Amalias far är vår stamfader på släktträdet, så det kändes lite \'personligt ansvar\' att få till ett bra manus. Själva händelsen är bara ett par meningar i släktboken, så det blev en utmaning att fylla i luckorna och väva samman en intressant historia.<BR><BR>Den största utmaningen var att få till dialogerna a la 1800-tal, utan att det kändes konstlat. Den största aha-upplevelsen var att man faktiskt pratade på nästan samma sätt då som nu. <BR><BR>Resultatet blev en kortfilm på tjugo minuter inspelad till stor del i Halmstad. Mycket tid har lagts ner på att hitta rätta scenografi och kläder. <BR><BR>Produktionstiden från att jag fick uppdraget i min hand till filminspelningen började var cirka tio månader, så det var snabba ryck att få den färdig.</span>',
      'textPin':'Filmen om Amalia baseras på en sann historia om Amalia Meuller från Halmstad.',
      'caseInputDate':'2015-02-24',
      'showArt':'0',
      'quote':'Steffo Dimfelt sätter lupp på saker i vår vardag, ofta på ett slagfärdigt sätt och med en komisk absurd knorr. I vårt arbete med Amalia var det något annorlunda då historien baserades på verkliga händelser 1890-talets Tylösand. Men i det ganska allvarliga dramat kan man ändå skönja Steffo Dimfelts karaktäristiska värme och humor.',
      'quoteName':'Mikael Berg<BR>Regissör',
      'type':'Kortfilm, 23min',
      'colorSpace':'1',
      'employer':'3',
      'imgCollage':'11',
      'imgCollageSetup':'8,6,7,14',
      'tools':'15',
      'tasks':'1',
      'format':'RED',
      'year':'2010',
      'link':null,
      'linkName':null,
      'imgThumb':'https://raw.githubusercontent.com/steffodimfelt/steffodimfelt.github.io/master/static/img/cases/film/2x1_amalia01.jpg'
    },
    {
      'id':'4',
      'show':'1',
      'headline':
      'Friskis&Svettis, Katalog V.15',
      'textShort':'Foto till Friskis&Svettis klädkataloger.',
      'textLong':'<span class=\'CapUp\'>Jag har producerat alla produktbilder<span> <span class="CapDown">till samtliga Friskis&Svettis-kataloger ända sedan 2005. Till Höst 2014- och Vår 2015-katalogerna fick jag även fota miljöbilderna på plats i en av Friskis-lokalerna i Stockholm.<BR><BR>Modellerna är utvecklingsansvariga på Friskis, och de fick gå loss på diverse stationer i lokalen. <BR><BR>Fotona fick ett modernt Instagram-stuk över sig, men retuschen är faktiskt minimal. Egentligen bara en gul och lila färgsättning och en polaroid-ram.<BR><BR>Eftersom de bilderna skulle kännas spontana gav vi inte modellerna mer anvisningar än: \'Gör som du normalt skulle göra\'. Porträttbilderna är något mer arrangerade. Den stående anvisningen var: \'Titta dit\' och så fick jag springa runt och fota.<BR><BR>Jag har bara fått bra respons över just den spontana bildkänslan. Jag jobbade mycket med kort skärpedjup vilket gjorde att man kom nära inpå modellerna.</span>',
      'textPin':'Fotning och slutoriginal av katalog.',
      'caseInputDate':'2015-03-16',
      'showArt':'0',
      'quote':null,
      'quoteName':'',
      'type':'Katalog',
      'colorSpace':'2',
      'employer':'4',
      'imgCollage':'10',
      'imgCollageSetup':'15,18,16,17',
      'tools':'1,4,16',
      'tasks':'9,12,16,17,18,19,22,23',
      'format':'-',
      'year':'2014',
      'link':null,
      'linkName':null,
      'imgThumb':'https://raw.githubusercontent.com/steffodimfelt/steffodimfelt.github.io/master/static/img/cases/print/2x1FriskisV15_4.jpg'
    },
    {
      'id':'5',
      'show':'1',
      'headline':'Ahlsell, Personalkläder',
      'textShort':'Katalog till Ahlsells personalkläder.  ',
      'textLong':'<span class=\'CapUp\'>Till Ahlsells katalog<span> <span class="CapDown">fick jag helhetsuppdraget att ta fram produktkatalogen.<BR><BR>Förutom att vara AD och originalare av katalogen, tog jag även fram ett koncept för miljöbilderna. Koncepetet blev en dag i en butik, där bilderna var olika tidsmässiga nedslag och situationer. Jag jobbade tillsammans med fotografen på plats i Ahlsell-butik, där tre anställad Ahlsell-medarbetare agerade modeller. <BR><BR>Dessutom fotade jag alla kläderna på modeller i studio. Det var hektiskt för jag jobbade parallellt med Svenska Spels katalog.</span>',
      'textPin':'Katalog till Ahlsells personalkläder. ',
      'caseInputDate':'2015-03-28','showArt':'0',
      'quote':null,'quoteName':'',
      'type':'Katalog',
      'colorSpace':'2',
      'employer':'2',
      'imgCollage':'9',
      'imgCollageSetup':'19,20,21,23',
      'tools':'1,4,16',
      'tasks':'9,12,16,17,18,19,23',
      'format':'210mm x 250mm<BR>40 sidor',
      'year':'2007',
      'link':null,
      'linkName':null,
      'imgThumb':'https://raw.githubusercontent.com/steffodimfelt/steffodimfelt.github.io/master/static/img/cases/print/2x1-Ahlsell01.jpg'
    },
    {
      'id':'6',
      'show':'1',
      'headline':'Ekoskotern Elektro 1',
      'textShort':'Logotype till elskotern Elektro 1. ',
      'textLong':'<span class=\'CapUp\'>Ecoskoter startade upp en import<span> <span class="CapDown">av elskotrar till Sverige. De behövde en logotype som skulle sättas på sidan av skotrarna. Premisserna var att den skulle kännas \'vespa\' samtidig som den skulle spegla att skotern gick på el. <BR><BR>Logotypeen fick klassisk framåtlutad våg, inspirerad av Leica och Campagnolo, som avslutas med en illustrerad stickkontakt. Klassiskt möter modernt.</span>',
      'textPin':'Logotype till elskotern Elektro 1.',
      'caseInputDate':'2015-04-13',
      'showArt':'0',
      'quote':null,'quoteName':'',
      'type':'Logotype',
      'colorSpace':'3',
      'employer':'5',
      'imgCollage':'3',
      'imgCollageSetup':'25,26,27',
      'tools':'2',
      'tasks':'28,10,26,27',
      'format':'-',
      'year':'2010',
      'link':null,
      'linkName':null,
      'imgThumb':'https://raw.githubusercontent.com/steffodimfelt/steffodimfelt.github.io/master/static/img/cases/other/2x1-Elektro02.jpg'
    },
    // {
    //   'id':'7',
    //   'show':'1',
    //   'headline':'Detaljbilder',
    //   'textShort':'\'The Devil is in the details\' brukar man ju säga. Att fota produkter innebär inte bara att ta en bild på en produkt.',
    //   'textLong':'<span class=\'CapUp\'>\'The Devil is in the details\'<span> <span class="CapDown">brukar man ju säga. Att fota produkter innebär inte bara att ta en bild på en produkt - man måste även förstå vad som avbildas. När man tar produktbilder ser man oftast hela produkten med en vit bakgrund. Detta för att en sådan bild är enkel att använda till en massa olika medier. Det är tydligt och man förstår vad det är man ser. <BR><BR>Men ibland behöver man ta ett par extra bilder. Oftast för att show detaljerna på produkten. Inget konstigt med det. <BR><BR>Mitt jobb blir genast lite roligare och utmanande. Att få gå närmare in i produkten och show dess \'själ\'. Sådant tycker jag är kul. Vissa gånger får man verkligen vända och vrida på både bildvinkel och produkt innan det blir rätt. Andra gånger lyckas man på första försöket. <BR><BR>När man väl är klar och har en jättebra bild, har man inte bara förtydligat produkten, man förmodligen även höjt värdet på produkten genom bilden.</span>',
    //   'textPin':'\'The Devil is in the details\' brukar man ju säga.',
    //   'caseInputDate':'2015-04-14',
    //   'showArt':'0',
    //   'quote':null,
    //   'quoteName':'',
    //   'type':'Produktfoto',
    //   'colorSpace':'1',
    //   'employer':'4',
    //   'imgCollage':'4',
    //   'imgCollageSetup':'28,29,30,31',
    //   'tools':'16,17,1',
    //   'tasks':'17,19,23,12,16',
    //   'format':'Canon RAW',
    //   'year':'2014',
    //   'link':null,
    //   'linkName':null,
    //   'imgThumb':''
    // },
    {
      'id':'8',
      'show':'1',
      'headline':'Svenska Spel, profilkollektion katalog',
      'textShort':'Svenska Spel behövde en katalog till sin kollektion. ',
      'textLong':'<span class=\'CapUp\'>Svenska Spel behövde en egen kollektion<span> <span class="CapDown">som spelombuden skulle ha på sig. Varje spel fick en egen linje, baserad på spelets färg som samtidigt hölls helhet genom att alla plagg hade samma uppbyggnad vad det gäller revär och stripes. <BR><BR>Mitt uppdrag var att ta produktfoton på hela kollektionen, på modell. Vi använde oss av ett par anställda på byrån.<BR><BR>Efter att alla produktfotona var tagna var det min uppgift att säkra upp och korrigera färgerna. Dels skulle alla färgerna hålla ihop med övriga spelens färger, dels skulle färgerna stämma på de olika plaggen. <BR><BR>Utmaningen var att hålla tempo och planera fotograferingen. Alla plaggen var inte klara och en del av dem fick färgkorrigeras. Dessutom hade jag dubbel deadline eftersom jag samtidigt jobbade med en katalog till Ahlsell.</span>',
      'textPin':'Profilkollektionkatalog till Svenska Spel.',
      'caseInputDate':'2015-04-14',
      'showArt':'0',
      'quote':null,
      'quoteName':'',
      'type':'Katalog',
      'colorSpace':'2',
      'employer':'2',
      'imgCollage':'8',
      'imgCollageSetup':'33,34,35,32',
      'tools':'16,1,4',
      'tasks':'9,12,16,17,18,19,23',
      'format':'210mm x 210 mm<BR>36 sidor',
      'year':'2007',
      'link':null,
      'linkName':null,
      'imgThumb':'https://raw.githubusercontent.com/steffodimfelt/steffodimfelt.github.io/master/static/img/cases/print/2x1-SvS-Katalog01.jpg'
    },
    {
      'id':'9',
      'show':'1',
      'headline':'Metallicas webbsidor',
      'textShort':'Historien om Metallicas webbsidor 1999-2003.',
      'textLong':'<p><span class=\'CapUp\'>Sommaren 1999 ringde Niclas Swanlund<span> <span class="CapDown">mig från San Fransisco. Vi kände inte varandra. Han hade fått mitt nummer av en gemensam vän. Han ville uppdatera Metallicas samtliga webbsidor - Metallica.com, MetOnTour.com och MetClub.com. \'Javisst!\', sa jag. \'Inga problem!\' Så här i efterhand var det tur att jag inte visste vilken vansinnig id\u00e9 det var.<BR><BR><h3>Bakgrund</h3>Niclas jobbade som turn\u00e9fotograf och ansvarig för Metallica på webben. På den tiden, i slutet av 90-talet, var webben fortfarande något som flödade av fria tankar, drömmar och något som bara var roligt att hålla på med. Niclas hade dock ett mål - han ville göra den bästa hårdrockssidan som fanns. <BR><BR>Vi kollade runt och det fanns faktiskt inga sidor som var särskilt bra, förutom Iron Maiden och Ozzy Osburn. Att bygga sitt varumärke på webben var ett okänt begrepp. Det vara knapp att folk visste vad webben var för något. <BR><BR><h3>Planen</h3>Vår id\u00e9 vara som sagt att bygga den bästa hårdrockssidan. Metallicas fans är mycket dedikerade till bandet och vår plan var att ge dem ALLT som Metallica har gjort. Att ge cred till fansen är något som är viktigt för bandet och det var det vi ville spegla på sidorna. För det var inte bara en webbsidor som skulle göras, utan tre stycken.<BR><BR><h3>Grundarbetet</h3>Jag hade byggt en del i Flash och runt 1999-2000 var det den teknik som var det häftigaste man kunde göra. Niclas hade inte själv några invändningar, hans inställning var bara att sidan skulle ligga i tekniskt framkant, vilket passade bra med Flashtekniken.<BR><BR>Tillsammans skissade vi upp sidan. Metallica hade då precis släppt sitt album S&M samarbetade med Anton Corbijn till sina officiella bandfoton. Dessa man\u00e9r kom att spegla i sidornas grafik.<BR><BR><h3>Utförande</h3>Hela hösten 1999 och våren 2000 satt jag mer eller mindre varje kväll mellan 21-03, eftersom klockan då var 9 på morgonen på amerikanska västkusten, och jobbade med sidan. Nuförtiden skulle det vara ett helt team som utvecklade sidan, men då var det bara jag. Niclas satt i San Fransisco och styrde upp vad som behövdes och kom med allt material medan jag satte ihop sidorna så fort det gick. <BR><BR>Någon gång i mitten av hösten slog det Niclas att det här med Flash inte var så användarvänligt. Man ska komma ihåg att i slutet av 90-talet fanns det ett stort problem i att alla besökare inte hade en modern webbläsare och om de hade det, så var de tvungna att ladda hem den senaste Flash-läsare. Vår lösning blev en Flash-sida och en HTML-variant. Och eftersom detta var innan ASP slagit igenom ordentligt, så fick jag hårdkoda varje sida för sig. <BR><BR>idag hade jag jobbat med databaser och mallade sidor, men då hade jag ingen aning om hur man programmerade. Dessutom fungerade Flash utan att man behövde scripta någonting. Problemet var att allt blev fruktansvärt tungrott. <BR><BR>Särskilt minns jag att alla låtar från alla album skulle vara med som provlyssning i både RealAudio och Quicktime. Att lista upp låtarna i HTML gick väl hyfsat snabbt, men i Flash var det inte roligt - jag vill minnas att den sida som man såg i Flash inte var samma som den som man såg i webbläsaren. Det innebar att jag manuellt fick justera varje sångrad för hand.  <BR><BR>MetClub och MetOnTour var enklare. De gjordes inte i Flash. MetClub är fansens sida, och den fick en vit variant av den svart som var Metallica.com. MetOnTour är turn\u00e9sidan och den fick dubbla sidor, för vi ville ha in lite rörliga bilder. <BR><BR><h3>Slutförande</h3>Strax innan sommaren 2000 blev allting klart. Vi var nöjda. Bandet var nöjda. Sidan fick ett enormt bra mottagande av fansen. Det var inte likt något som funnits i hårdrockssfären. Det mest galna var att allt var hårdkodat och gjort av två personen. Ibland tänker jag på den tanken - världens bästa hårdrocksband gjordes av två personen. <BR><BR><h3>Efterspel</h3>Det blev snack om att vi skulle ha en lanseringsfest i San Fransisco. Jag blev glad. \u00c4ntligen skulle jag få träffa bandet och det kändes som att festen var för mig och mitt hårda arbete. Festen skulle vara på en stripklubb (såklart) och bandet skulle spela. Basisten Jason Newsted hade precis slutat och man hade utlyst en tävling om att få spela med Metallica, som basist, under kvällen. Jag bokade resa för min bror och mig.<BR><BR>Men ibland blir det inte som man önskar. Under sommaren blev James inlagd på avgiftning och bandemedlemmarna behövde vara ifrån varandra. Alla deras uppdrag stoppades, så även lanseringsfesten. Tråkigt, men jag och min bror hade redan bokat resa och vi fick i varje fall tre veckor i USA. <BR><BR>Så här i efterhand är det fortfarande overkligt att jag har gjort Metallicas sida. Jag har träffat många diehard-fans som skulle vilja göra den. Ibland blir jag påmind om det och varje gång blir jag glad och stolt. Säga vad man vill om att det var 15 år sedan, men det var jag som gjorde det!</span>',
      'textPin':'Historien om Metallicas webbsidor 1999-2003.',
      'caseInputDate':'2015-04-16',
      'showArt':'0',
      'quote':'\'Fuckin\' great, man!\'',
      'quoteName':'James Hetfield, Sångare',
      'type':'Webbsidor',
      'colorSpace':'1',
      'employer':'6',
      'imgCollage':'9',
      'imgCollageSetup':'36,54,55,56',
      'imgThumb': 'https://raw.githubusercontent.com/steffodimfelt/steffodimfelt.github.io/master/static/img/cases/web/2x2-Metallica02.jpg',
      'tools':'1,10,14',
      'tasks':'7,8,10,16,38,39',
      'format':'HTML<BR>Flash',
      'year':'1999',
      'link':null,
      'linkName':null 
    },
    {
      'id':'11',
      'show':'1',
      'headline':'Skandia, Produktlansering ',
      'textShort':'Inspirationsbilder till Skandias produktfolder. ',
      'textLong':'<span class=\'CapUp\'>När Skandia gjorde om sin profil<span> <span class="CapDown">hade det föregåtts av en hel del turbulens. Man insåg att man behövde byta bort sin gamla kostym och paraply och föra in något nytt. Inget konstigt med det. Alla stora företag gör det med jämna mellanrum. <BR><BR>Skandias nya profil var allt annat än företagsblå. Man tog en grön färg istället. Man tog fram en ny logotype med namnet \'Skandia\' och adderade ett kolon i silver efter namnet. <BR><BR>Vårt uppdrag blev att använda oss av kolona och färgerna på produkter. Det blev som ett mönster i både grund- och accentfärger. <BR><BR>För att riktigt vända blad, ville man även skapa ett event på sitt huvudkontor. Till detta event skapades en utställning och till denna utställning behövdes det en inspirerande folder med produkter. <BR><BR>För att göra en lång historia kort - jag fotade inspirationsbilderna till foldern och till säljmaterialet. Jag gjorde även förpackningar, ansvarade för webbshop och material till en lanseringsmonter för deras huvudkontor.</span>',
      'textPin':'Inspirationsbilder till Skandias produktfolder. ',
      'caseInputDate':'2015-04-17',
      'showArt':'0',
      'quote':null,
      'quoteName':'',
      'type':'Inspirationsfoton',
      'colorSpace':'1',
      'employer':'2',
      'imgCollage':'3',
      'imgCollageSetup':'45,44,43',
      'tools':'16,1',
      'tasks':'12,16,17,19',
      'format':'-',
      'year':'2008',
      'link':null,
      'linkName':null,
      'imgThumb':'https://raw.githubusercontent.com/steffodimfelt/steffodimfelt.github.io/master/static/img/cases/foto/2x1-Skandia-lansering03.jpg'
    },
    {
      'id':'10',
      'show':'1',
      'headline':'Friskis&Svettis, Produktaffisch V16',
      'textShort':'Plaggen i Friskis affisch gjordes helt i 3D.',
      'textLong':'<span class=\'CapUp\'>Affisch till Friskis<span> <span class="CapDown">föregås av att under mina tio år som jag jobbat med Friskis, så har det skickats ut kataloger. Förutom några år tidigare, det gjordes både en affisch och en katalog. <BR> Till Vår 16 tänkte produktansvarig att det skulle vara på sin plats att bara göra en affisch. I diskutionen kom vi även fram till att det var mycket nytt som skulle shows, men att plaggen inte fanns i produktion. Tanken blev att göra alla produkter i 3D, istället för att blanda foto på befintliga produkter med skisser. <BR><BR>På en månad modellerades plaggen, sattes på rätt textur och renderades. Resultatet användes till affisch och webshop.</span>',
      'textPin':'Plaggen i Friskis affisch gjordes helt i 3D.',
      'caseInputDate':'2015-04-16',
      'showArt':'1',
      'quote':null,
      'quoteName':'',
      'type':'Affisch',
      'colorSpace':'2',
      'employer':'4',
      'imgCollage':'10',
      'imgCollageSetup':'42,41,39,38',
      'tools':'20,1,3',
      'tasks':'13,12,15,20,16',
      'format':'594mmx840mm',
      'year':'2015',
      'link':null,
      'linkName':null,
      'imgThumb':'https://raw.githubusercontent.com/steffodimfelt/steffodimfelt.github.io/master/static/img/cases/print/2x1-Friskis-Affisch-06.jpg'
    },
    {
      'id':'12',
      'show':'1',
      'headline':'TeliaSonera, Informationspelare',
      'textShort':'Informationspelare till TeliaSoneras bolagsstämma.',
      'textLong':'<span class=\'CapUp\'>Till varje bolagsstämma<span> <span class="CapDown">vill man som företag show upp det mest intressanta som hänt under året och saker som komma skall. <BR><BR>Aktieägare kommer för att ta del av framtiden och bolagstämmor brukar var välbesökta, särskilt när det kommer till stora företag som exempelvis TeliaSonera. <BR><BR>Platser för 2004 års bolagsstämma var på Annexet vid Globen i Stockholm.<BR><BR>För att få ut maximal exponering på en begränsad yta, använde vi hexagonformade pelare. Som besökare kan man dels få en lättfattlig överblick över TeliaSoneras hela verksamhet, samtidigt som man slipper trängas i fall det är något man vill läsa mer om.<BR><BR>Pelarnas placering ger också ett flöde från själva lounge-delen in  till bolagstämmans sal.</span>',
      'textPin':'Informationspelare till TeliaSoneras bolagsstämma.',
      'caseInputDate':'2015-04-20',
      'showArt':'0',
      'quote':null,
      'quoteName':'',
      'type':'Informationspelare',
      'colorSpace':'2',
      'employer':'7',
      'imgCollage':'7',
      'imgCollageSetup':'47,46,48,49',
      'tools':'1,2',
      'tasks':'9,10,16',
      'format':'-',
      'year':'2004',
      'link':null,
      'linkName':null,
      'imgThumb':'https://raw.githubusercontent.com/steffodimfelt/steffodimfelt.github.io/master/static/img/cases/print/1x1-TeliaSonera-Hex-03.jpg'
    },
    {
      'id':'13',
      'show':'1',
      'headline':'Scandic, VIP-gåva',
      'textShort':'3D-skiss på Scandics VIP-gåva.',
      'textLong':'<span class=\'CapUp\'>Ibland behövs det något extra.<span> <span class="CapDown">När det skulle göras en VIP-gåva till Scandics bästa gäster, gjorde jag skisser i 3D. Dels för att det är ett lätt sätt att visualisera produkten och dels för att show att vi verkligen såg detta som en VIP-gåva. <BR> <BR><BR>Utifrån skisser från produktansvarig, ritade jag upp necessären i 3D. När jag fått godkänt av ansvarig, gick jag vidare i processen.   <BR><BR> Jag tog textur från en provbit och slutligen renderade jag ut skissen.  <BR> <BR><BR>Som slutlig touch ritade jag upp en bit av ett badrum och satte jag in necessären där.</span>',
      'textPin':'3D-skiss på Scandics VIP-gåva.',
      'caseInputDate':'2015-04-20',
      'showArt':'0',
      'quote':null,
      'quoteName':'',
      'type':'3d-skiss',
      'colorSpace':'1',
      'employer':'2',
      'imgCollage':'9',
      'imgCollageSetup':'53,50,51,52',
      'tools':'3,1',
      'tasks':'13,4,12,15,16,19,20,23',
      'format':'-',
      'year':'2011',
      'link':null,
      'linkName':null,
      'imgThumb':'https://raw.githubusercontent.com/steffodimfelt/steffodimfelt.github.io/master/static/img/cases/3d/2x1-Scandic-Necessar-04.jpg'
    },
    {
      'id':'14',
      'show':'1',
      'headline':'Swedbank, Serviceshop',
      'textShort':'En enkel shoplösning till Swedbanks Servicelager.',
      'textLong':'<span class=\'CapUp\'>Att göra enkla lösningar<span> <span class="CapDown">som blir bra, kräver kunskap. När Swedbank ville ha en beställningslösning till sin interna serviceshop på huvudkontoret, skulle den närmaste lösningen vara att ta en befintlig shop och göra en variant av den. Detta skulle bli både oeffektiv både i kostnad och i arbete. Istället skissade jag upp ett förslag som gjorde det snabbt och enkelt  att beställa och adminstrera. <BR><BR>Swedbank har ett tjugotal VIP-produkter som ligger internt på huvudkontoret. Som anställd kan man beställa och hämta ut en produkt på Servicelagret. Denna beställning ville man göra effektivare genom att man skulle kunna beställa via mejl. <BR><BR>Min lösning blev ett enkelt formulär som vid beställning skickade bekräftelser till beställaren och till en central mejladress. Detta gjorde att Servicelagret fick bättre kontroll över vad som ska hämtas. Dessutom lade jag till en bekräftelse till produktleverantören och en byggde en enkel administrationssida. Självklart gjordes allt responsivt.</span>',
      'textPin':'En enkel shoplösning till Swedbanks Servicelager.',
      'caseInputDate':'2015-04-29',
      'showArt':'0',
      'quote':null,
      'quoteName':'',
      'type':'Webshop',
      'colorSpace':'1',
      'employer':'4',
      'imgCollage':'2',
      'imgCollageSetup':'57,58',
      'tools':'7,8,9,11,19',
      'tasks':'7,8,29',
      'format':'Responsiv webb',
      'year':'2015',
      'link':null,
      'linkName':null,
      'imgThumb':'https://raw.githubusercontent.com/steffodimfelt/steffodimfelt.github.io/master/static/img/cases/web/2x1Swedbank-Shop03.jpg'
    },
    {
      'id':'15',
      'show':'1',
      'headline':'Johnnie Walker, Förpackning',
      'textShort':'Grafisk design till både förpackning och whiskeyglas.',
      'textLong':'<span class=\'CapUp\'>Jag hade knappt jobbat två månader<span> <span class="CapDown">på Stadium Promotion när jag fick uppdraget att göra grafisk design till både förpackning och whiskeyglas. Glasen var VIP-gåvor som skulle delas ut vid speciella event. <BR><BR>Bakgrunden var att Johnnie Walker sponsrade McLaren Mercedes förare Kimi Raikkonen. Man hade dessutom blivit Formula 1 officiella whiskey. Johnnie Walker ville ha en racingkänsla i förpackningen och att glasen skulle kännas lite exklusiva.<BR><BR>Jag gjorde ett par varianter på Kimi på förpackningen och jag tog fram ett glas där hans autograf skulle blästras in. Efter några turer hos kund blev det tyvärr ingen autograf och blästringen blev av tidsskäl en silvrig etikett med Johnnie Walkers logotype. <BR><BR>Det trevliga är att jag lyckades få till logotypeens placering. Dess överkant är en indikator på ca 2cl härlig Black Label. <BR><BR>Trots att det har gått så lång tid sedan jag gjorde glasen, är det fortfarande ett av de jobb som jag är mest stolt över.</span>',
      'textPin':'Grafisk design till både förpackning och whiskeyglas.',
      'caseInputDate':'2015-05-08',
      'showArt':'0',
      'quote':null,'quoteName':'',
      'type':'Förpackning',
      'colorSpace':'2',
      'employer':'2',
      'imgCollage':'6',
      'imgCollageSetup':'61,62,63',
      'tools':'1,2,4',
      'tasks':'9,10,12,16,27',
      'format':'Förpackning<BR>Whiskeyglas',
      'year':'2005',
      'link':null,
      'linkName':null,
      'imgThumb':'https://raw.githubusercontent.com/steffodimfelt/steffodimfelt.github.io/master/static/img/cases/print/2x1-JW-Whiskey-03.jpg'
    },
    {
      'id':'16',
      'show':'1',
      'headline':'Telia, Illustrationer',
      'textShort':'Illustrationer till sportflaska och musmatta.',
      'textLong':'<span class=\'CapUp\'>Ibland blir jobbet både enkelt och roligt.<span> <span class="CapDown">Det behövdes några illustrationer på produkter till Telia som bland annat använder sig av heldragna linjer som ritar upp grafiska bilder. Mycket stilfull. Och utmanande. <BR><BR>Kundansvarig behövde en sportflaska med ett sportmotiv och en musmatta med en datormus. Helst skulle linjen inte brytas, men det var okej om det inte märktes. Eftersom jag helst inte gör saker halvhjärtat, så var målet att göra heldragna linjer solklart. <BR><BR>När man gör ett sådant här jobb verkar det alltid enkelt till en början, men det ställer krav på kreativt tänk - Linjen får inte var för tjock, inte vara för nära andra delar, den ska sitta ihop på ett vettigt sätt och framför allt ska man se vad det föreställer. <BR><BR>Som vanligt blir det många skisser innan slutoriginalet kan skickas iväg. Kunden var så nöjd med resultatet att de godkände illustrationerna på stående fot.</span>',
      'textPin':'Illustrationer till sportflaska och musmatta.',
      'caseInputDate':'2015-05-07',
      'showArt':'0',
      'quote':null,
      'quoteName':'',
      'type':'Produktillustrationer',
      'colorSpace':'4',
      'employer':'4',
      'imgCollage':'8',
      'imgCollageSetup':'67,64,66,65',
      'tools':'2',
      'tasks':'9,10,26',
      'format':'Illustrationer',
      'year':'2014',
      'link':null,
      'linkName':null,
      'imgThumb':'https://raw.githubusercontent.com/steffodimfelt/steffodimfelt.github.io/master/static/img/cases/other/2x1-Telia-Sport-02.jpg'
    },
    {
      'id':'17',
      'show':'1',
      'headline':'Löfbergs Lila, Butikskampanj',
      'textShort':'Butikskampanj för Löfbergs Lila.',
      'textLong':'<span class=\'CapUp\'>2006 firade Löfbergs Lila 100år.<span> <span class="CapDown">I samband med det tog man fram ett par illustrationer som skulle representera de olika decennierna. <BR><BR>Mitt uppdrag blev att ta fram mönsteroriginal till kopparna och de magneter som man skulle få i samband med kaffekoppsköpet.<BR><BR>Eftersom detta var en butikskampanj behövdes det även lådor och ställ. Magneterna skulle levereras i kartonger till butikerna och Löfbergs Lila ville han smart lösning som även stack ut lite och skapade intresse i butiken. <BR><BR>Tillsammans med min projektledaren arbetade vi fram en kartonglösning, där illustrationerna stack upp när man vek ner ovankanten på kartongen de fraktades i. Hela kartongen kunde man sedan sätta i en pelare, som vi också tog fram, eller ställa direkt på ett bord ihop med kaffekopparna.\u00a0</span>',
      'textPin':'Butikskampanj för Löfbergs Lila.',
      'caseInputDate':'2015-05-19',
      'showArt':'0',
      'quote':null,
      'quoteName':'',
      'type':'Butikskampanj',
      'colorSpace':'2',
      'employer':'2',
      'imgCollage':'2',
      'imgCollageSetup':'73,72',
      'tools':'1,2',
      'tasks':'9,25',
      'format':'Butiskpresentation<BR>Magneter<BR>Koppar',
      'year':'2006',
      'link':null,
      'linkName':null,
      'imgThumb':'https://raw.githubusercontent.com/steffodimfelt/steffodimfelt.github.io/master/static/img/cases/print/2x1-Lofbergs-Camp-03.jpg'
    },
    {
      'id':'18',
      'show':'1',
      'headline':'Friskis&Svettis, Informationsfilm',
      'textShort':' Informationsfilm till Friskis&Svettis.',
      'textLong':'<span class=\'CapUp\'>När Friskis&Svettis uppdaterade sin webbshop 2014<span> <span class="CapDown">gjordes det så många nya ändringar och tillägg att kundansvarig insåg att det bästa sättet att förklara alla ändringar var med en presentationsfilm. <BR><BR>Tillsammans med vår AD och vår copywrighter jobbade vi fram en id\u00e9 att göra den animerad i 3D. AD:n tog fram ett par skisser som jag kunde jobba vidare på och copyn skrev texterna som låg till grund för filmen. Sen var det upp till mig. <BR><BR>Det tog mig sex veckor från scratch att färdigställa filmen och hade även en del andra jobb som också skulle göras. <BR><BR>Deadline var ett caseInputDate när den nya shoppen skulle öppnas, så det var tight om tid. <BR><BR>Jag pushade verkligen mina kunskaper framåt, dels för att jag gjorde saker som jag aldrig gjort tidigare och samtidigt som jag skulle göra dem var jag tvungen att lära mig, dels hade jag en deadline, vilket gjorde att jag måste hitta kreativa lösningar för att inte bli sen. <BR><BR>Om jag inte minns fel, var jag klar kvällen innan, då hade jag en vecka tidigare hittat en renderingsfarm som hade ett bra erbjudande och som ökade produktionstakten märkbart mot slutet. \u00a0</span>',
      'textPin':' Informationsfilm till Friskis&Svettis.',
      'caseInputDate':'2015-05-18',
      'showArt':'0',
      'quote':null,
      'quoteName':'',
      'type':'Instruktionsfilm',
      'colorSpace':'1',
      'employer':'4',
      'imgCollage':'4',
      'imgCollageSetup':'68,69,70,71',
      'tools':'1,2,3,13',
      'tasks':'4,11,12,13,14,15,16,21,23,24,25',
      'format':'Instruktionfilm<BR>1920px x 1080px',
      'year':'2014',
      'link':'https//:vimeo.com128578317',
      'linkName':'Friskis&Svettis, Instruktionsfilm 2014',
      'imgThumb':'https://raw.githubusercontent.com/steffodimfelt/steffodimfelt.github.io/master/static/img/cases/film/2x1-Friskis-Instr-04.jpg'
    },
    {
      'id':'19',
      'show':'1',
      'headline':'Scandic, Hangtags',
      'textShort':'Hangtags till produkter i hotellshopparna.',
      'textLong':'<span class=\'CapUp\'>Varke Scandichotell har en lite butik i foaj\u00e9n.<span> <span class="CapDown">När Scandic skaffade sig ett nytt profil, blev vårt uppdrag att ta fram passande produkter till butikerna. Produkterna var av karaktären \'Jag glömde visst...hemma\'. Det var vinöppnare, klädborstar, sykit, badkläder, tvättpåsar med mera. <BR>Grundtanken var att de inte skulle förpackas utan man skulle direkt se vad som låg på hyllorna. <BR>Lösningen blev att sätta hangtags på alla produkterna.<BR>Jag fick i uppdrag blev att ansvara för foto och retusch av alla produkterna, göra dem tryckfärdiga och montera dem på mallarna till hangtagsen. <BR>Förutom produktfotograferingretush ansvarade jag även för originalhanteringen och kontakt med \u00a0tryckeriet.\u00a0</span>',
      'textPin':'Hangtags till produkter i hotellshopparna.',
      'caseInputDate':'2015-05-27',
      'showArt':'0',
      'quote':null,
      'quoteName':'',
      'type':'Hangtags',
      'colorSpace':'2',
      'employer':'2',
      'imgCollage':'7',
      'imgCollageSetup':'99,100,101,102',
      'tools':'1,2,16',
      'tasks':'9,12,16,17,23',
      'format':'Hangtags<BR>Klisteretiketter',
      'year':'2008',
      'link':null,
      'linkName':null,
      'imgThumb':'https://raw.githubusercontent.com/steffodimfelt/steffodimfelt.github.io/master/static/img/cases/print/2x1-Scandic-Hangtags02.jpg'
    },
    {
      'id':'20',
      'show':'1',
      'headline':'Ahlsell, Grafiskt mönster',
      'textShort':'Mönster till olika typeer av produkter.',
      'textLong':'<span class=\'CapUp\'>Ahlsell behövde grafik<span> <span class="CapDown">till sina produkter. Man ville förnya sig på något sätt men samtidigt ville man inte gå för långt. Det skulle vara en egen grafisk enhet för produkter, snarare än en ny profil för hela företaget. Och det skulle kännas \'Ahlselligt\'.<BR><BR>Man hade redan använt sig av enfärgade rutmönster. Det jag gjorde var att vidareutveckla rutnätet, malla upp bilder och lägga till komplementfärger där det gavs möjlighet. <BR><BR>Många produkter kunde bara tryckas med enfärgstryck lösningen då blev ett raster som gjorde att färgen upplevdes som tonad. <BR><BR>Mönstret användes ett par år, innan man uppdaterade sig igen med nya grafiska element.</span>',
      'textPin':'Mönster till olika typeer av produkter.',
      'caseInputDate':'2015-05-26',
      'showArt':'0',
      'quote':null,
      'quoteName':'',
      'type':'Produktmönster','colorSpace':'5',
      'employer':'2',
      'imgCollage':'5',
      'imgCollageSetup':'82,80,81,83,84',
      'tools':'1,2,4',
      'tasks':'28,9,10,26,27',
      'format':'Produktmönster',
      'year':'2007',
      'link':null,
      'linkName':null,
      'imgThumb':'https://raw.githubusercontent.com/steffodimfelt/steffodimfelt.github.io/master/static/img/cases/print/2x1-AHL-rutor-06.jpg'
    },
    {
      'id':'21',
      'show':'1',
      'headline':'Ahlsell, Produktlåda',
      'textShort':'Mönster till produktlåda.',
      'textLong':'<span class=\'CapUp\'>Ahlsells produktlåda<span> <span class="CapDown">gjordes utifrån det grafiska man\u00e9 som jag tog fram för Ahlsells produkter. <BR><BR>Lådorna innehöll godis men kunde lika gärna användas för exempelvis golbollar eller vad man nu behöver vid olika event. <BR><BR>Det speciella med lådorna är den blandar fyrfärgstryck och Ahlsells blå Pantone-färg. Detta för att få fram den perfekta Ahlsell-blå nyansen. <BR><BR>Utmaningen var att få det övriga trycket att bli lika intensivt som en ren Pantone. Det tog några provtryck och skruvningar på mättnaden innan jag och kunden var nöjda.\u00a0</span>',
      'textPin':'Mönster till produktlåda.',
      'caseInputDate':'2015-05-27',
      'showArt':'0',
      'quote':null,
      'quoteName':'',
      'type':'Produktlåda',
      'colorSpace':'5',
      'employer':'2',
      'imgCollage':'2',
      'imgCollageSetup':'86,87',
      'tools':'1,2',
      'tasks':'9,10,16,25',
      'format':'Höjd: 232mm<BR>Bredd: 265mm<BR>Djup: 127mm',
      'year':'2007',
      'link':null,
      'linkName':null,
      'imgThumb':'https://raw.githubusercontent.com/steffodimfelt/steffodimfelt.github.io/master/static/img/cases/print/2x2-AHL-kartong-02.jpg'
    },
    // {
    //   'id':'22',
    //   'show':'1',
    //   'headline':'Logotypeer',
    //   'textShort':'Ett urval av logotypeer.',
    //   'textLong':'<span class=\'CapUp\'>Jag har fått frågan ett antal gånger<span> <span class="CapDown">om jag kan göra en logotype.\u00a0<BR><BR>Lite lätt och snabbt...<BR><BR>Det är inte så lätt som man tror. Man behöver göra ett ordentligt grundjobb och faktiskt värka ut logotypeen.<BR><BR>Det är många delar som ska höra ihop och framför allt tycker jag att den ska berätta en story om ägaren.\u00a0<BR><BR>Och om jag ska vara ärlig, så anser jag att jag hittills har gjort ett par bra jobb. Det finns en glädje i att se ett företag eller person få växa fram i en enda bild.<BR><BR>För mig ska en logotype berätta något om personenföretaget. Den ska helst kunna stå för sig själv, som en ikon. Och allra helst ska den ha en liten twist. <BR><BR> En logotype som inte finns här är till Ekoskoter, men du kan <h3>DANIJELA\u00a0RUNDQVIST</h3><p>Danijela är en god vän som behövde hjälp med sin blogg. Självklart fick hon en blogg och en logotype. Jag menar - klart att en hockeyhjältinna ska ha en ordentlig hockeylogotype.<BR><BR>Logotypeen har sitt ursprung från amerikanska hockeyvärlden med massiva bokstäver. Den har fått en svensk touch med gula stjärnor på blå \'ismoln\'. Q:et i Rundqvist har bytts ut mot en puck där ismolnen och stjärnorna blivit Q:ets svans. Stjärnorna representerar Danijelas fruktade slagskott.\u00a0<p><BR><BR><h3>NYREGISTRERING.SE</h3><p>Ett företag som tillhandahöll en tjänst där man månadsvis kunde få tillgång till nyregistrerade företag.\u00a0<BR><BR>Logotypeen utgår från bokstäverna n och r (ny\u00a0registering).\u00a0<BR><BR>Den \'studsande effekten\' från bokstäverna symboliserar att man behöver göra ett nedslag hos Nyregistrering.se för att kunna ta sig vidare till de intressanta företagen.\u00a0<p><BR><BR><h3>FATUHIVA\u00a0FILM</h3><p>Fatuhivas logotype hade en fristående figur i sin gamla logotype som jag renodlade och ramade in. Ramen är innerdelen av en filmcell, främst för att det är klich\u00e9aktigt med matarhål på en filmlogotype.\u00a0<p><BR><BR><h3>CHRISTIN\u00a0PHILIPSSON</h3><p>Christin är fotograf som behövde en enkel logotype och hon behövde den fort. Heslt skulle den vara lite personlig. Inget är bättre för kreativiteten än lite tidspress. Den mest personliga logotypeen man har är sin namnteckning. Varför inte? Det fick bli Christins autograf.\u00a0<BR><BR>För att göra det lite mer intressant ritade jag om den i 3D, vilket också gjorde att den fick en mjukare rundhet.<p></span>',
    //   'textPin':'Ett urval av logotypeer.',
    //   'caseInputDate':'2015-05-24',
    //   'showArt':'0',
    //   'quote':null,
    //   'quoteName':'',
    //   'type':'Logotypeer',
    //   'colorSpace':'1',
    //   'employer':'8',
    //   'imgCollage':'4',
    //   'imgCollageSetup':'76,77,78,79',
    //   'tools':'2,1,3',
    //   'tasks':'28,26,22',
    //   'format':'Vektorgrafik<BR>PNG<BR>JPG',
    //   'year':null,
    //   'link':null,
    //   'linkName':null,
    //   'imgThumb':'https://raw.githubusercontent.com/steffodimfelt/steffodimfelt.github.io/master/static/img/cases/other/2x1-Danni.jpg'
    // },
    {
      'id':'23',
      'show':'1',
      'headline':'Skandia, Sommarpresent',
      'textShort':'Sommarpresent till anställda på Skandia.',
      'textLong':'<span class=\'CapUp\'>Det första Skandia gjorde<span> <span class="CapDown">när de bytte sin profil, var att fråga efter en sommarpresent till alla anställda. Den skulle på något sätt binda ihop den nya profilen med sommar. <BR><BR>Produktansvarig tog fram två \'bollar\' som skulle representera de två punkter som numera finns i Skandias logotype. <BR><BR>Mitt uppdrag var att ta fram originalet till förpackningen.</span>',
      'textPin':'Sommarpresent till anställda på Skandia.',
      'caseInputDate':'2015-05-27',
      'showArt':'0',
      'quote':null,
      'quoteName':'',
      'type':'Presentlåda',
      'colorSpace':'2',
      'employer':'2',
      'imgCollage':'7',
      'imgCollageSetup':'91,89,90,92',
      'tools':'1,2',
      'tasks':'9,10,16,25',
      'format':'Höjd: 330mm<BR>Bredd: 250mm<BR>Djup: 100mm',
      'year':'2008',
      'link':null,
      'linkName':null,
      'imgThumb':'https://raw.githubusercontent.com/steffodimfelt/steffodimfelt.github.io/master/static/img/cases/print/2x2-Skandia-Summer-03.jpg'
    },
    {
      'id':'24',
      'show':'1',
      'headline':'Gör\'t, Projektplanerare',
      'textShort':'En egenutvecklad projektplanerare. ',
      'textLong':'<span class=\'CapUp\'>Vad gör man när man snabbt behöver en projektplanerare?<span> <span class="CapDown">Svaret är att man helt enkelt bygger en. <BR><BR>När jag var originalare på Stadium Promotion upptäckte vi att projekten ramlade in allt snabbare och vi fick allt mindre överblick om vem som var ansvarig för vad och vem som väntade på tillbakaspel och var projekten hade för tidsplan. <BR><BR>Att köpa in en projektplanerare är inte bara en kostnad, det är inte säkert att alla kommer att använda den, plus att den kanske inte passar i Stadium Promotions sätt att arbeta.<BR><BR>Mitt förslag blev att bygga en egen projektplanerare, som vi själva kunde anpassa till vårt arbetssätt och möjlighet att bygga ut efter behov. Jag hade vid tidpunkten för byggandet ännu inte lärt mig PHP varpå jag byggde den i Classic ASP, JavaScript och Access, under tre veckor (till och från eftersom jag hade andra tasks att sköta upptill).  Koderna kanske inte är de snyggaste och turerna kring att lägga in och ta bort poster är inte optimala, men med tanke på tiden så är jag nöjd med resultatet. <BR><BR>Gör\'t har en enkel struktur. Man lägger in sitt projekt, är det fler inblandade bockar man för deras namn, deras tasks och när man förväntar sig återspel från dessa personer. Man kan få upp en projektlista på alla projekt man själv har starta, men även de projekt som någon annan har startat och man själv är delaktig i. Ja, that\'s it! Mer än så hann jag inte med. Dock hade jag vidare planer på mejlfunktioner och grafisk projektstatus, men som sagt, tiden fanns inte. <BR><BR>Trots det antika ASP och att koppla ihop det med Access, är jag ändå nöjd med resultatet. De rådiga koderna syns inte utåt, som tur är. Det finns en tanke om att bygga om den i PHP och MySQL, men just nu har tiden inte räckt till.<BR><BR>Ordet Gör\'t är östsjötskt och betyder helt enkelt \'Gör det\' ocheller \'Redan gjort\'. Stadium var moderbolaget till Stadium Promotion och de satt i Norrköping.</span>',
      'textPin':'En egenutvecklad projektplanerare. ',
      'caseInputDate':'2015-05-28',
      'showArt':'0',
      'quote':null,
      'quoteName':'',
      'type':'Projektplanerare',
      'colorSpace':'1',
      'employer':'2',
      'imgCollage':'3',
      'imgCollageSetup':'93,94,95',
      'tools':'22,21,10,11,7,1',
      'tasks':'7,8,10',
      'format':'Webbsida',
      'year':'2012',
      'link':null,
      'linkName':null,
      'imgThumb':'https://raw.githubusercontent.com/steffodimfelt/steffodimfelt.github.io/master/static/img/cases/web/2x1-DoIt-02.jpg'
    },
    {
      'id':'25',
      'show':'1',
      'headline':'Stadium Promotion, Webbsida',
      'textShort':'Webbsida till Stadium Promotion.',
      'textLong':'<span class=\'CapUp\'>Det var snabba ryck med att göra Stadium Promotions webbsida.<span> <span class="CapDown">Jag hade precis avslutat case-filmerna som skulle vara på sidan, sommaren var en vecka bort.<BR><BR>Av erfarenhet vet jag att det är stört inpå omöjligt att byggga en schysst sida på en vecka. Det är stört på omöjligt. \u00c4ndå skulle det göras. <BR><BR>Som tur var fick jag bra underlag från min AD och Copy. Jag byggde sidan i Flash. Och fort gick det. Det var inte så många sidor som skulle göras.<BR><BR>På onsdag eftermiddag presenterade jag sidan. Vi upptäckte på en gång att sidan inte fungerade i alla läsare. Det behövdes göras en HTML5-variant. Jag satte genast igång att jag en konverterare.<BR><BR>Turligt nog för mig hade Google utvecklat en plugin till Flash som heter Swiffy. Den räddade mitt liv. <BR><BR>Fredag eftermiddag vid 18-tiden, kunde vi korkar upp champagnen och stå i Nöjdrutan över den nya snygga webbsidan och dess filmer.</span>',
      'textPin':'Webbsida till Stadium Promotion.',
      'caseInputDate':'2015-05-28',
      'showArt':'0',
      'quote':null,
      'quoteName':'',
      'type':'Webbsida',
      'colorSpace':'1',
      'employer':'2',
      'imgCollage':'6',
      'imgCollageSetup':'96,97,98',
      'tools':'14,23,19',
      'tasks':'7',
      'format':'Webbsida',
      'year':'2012',
      'link':'',
      'linkName':'',
      'imgThumb':'https://raw.githubusercontent.com/steffodimfelt/steffodimfelt.github.io/master/static/img/cases/web/2x2-SP-Webb-03.jpg'
    },
    {
      'id':'26',
      'show':'1',
      'headline':'Stadium Promotion, Casefilmer',
      'textShort':'Casefilmer till Stadium Promotion.',
      'textLong':'<span class=\'CapUp\'>\'Hur snabbt kan en person göra sju företagsfilm?\'<span> <span class="CapDown">Svaret är tre och en halv månad (och då jobbade jag tidvis med andra tasks också).<BR><BR>Filmerna var upprinnelsen i den process som pågått i nästan tre år på Stadium Promotion. Man ville omdefiniera det man lite slarvigt kallar för \'profilprodukter\' och istället slå sig in på en mer medveten del i marknadsföringsmixen och bli ett hållbart reklamalternativ. Vad är mer hållbart än en produkt, i bra kvalitet, som används dagligen? <BR><BR>Tillsammans med två andra medarbetare satte vi oss ner och spånade. En av id\u00e9erna som jag kom med var att göra korta filmer som repeterade sig själva. Fördelen med detta var att man kunde göra en kort film, men som kunde förlängas i en evig loop. Som alltid när det gäller vision och slutresultat, blev det några jämkningar, bland annat att just att filmerna skulle vara eviga loopar. Men att repetera filmerna fem sex gånger är tillräckligt. <BR>En annan sak var också att de skulle vara roliga. Humor är en genväg till gillandet och vi hade en grundtanke till alla filmerna. Nu var det bara att sätta igång.<BR><BR>\'Den som är ovetande om det omöjliga, gör det möjliga\' är en tanke så här efteråt. Visst - det fanns manus och id\u00e9er, men själva arbetsprocessen var mycket dynamisk, för att inte säga något obefintligt. Och det var nog det som gjorde det möjligt. <BR><BR>Jag fick använda alla medel och program för att ta mig igenom filmerna. De innehöll 3D-animeringar, rotoscoping, chroma key och lager på lager av compositing. Jag lärde mig en massa om arbetsflöden och tekniska utmaningar. Det var verkligen lärorikt att huvudstupa kasta sig ut för att lösa uppgiften innan semestern började.<BR><BR>Det blev bättre än jag trodde och med tanke på den snäva tidsramen är jag riktigt nöjd med resultatet. Det är klar - idag hade jag nog planerat och varit mer noggrann innan jag satte igång och testat lite, men samtidigt hade jag inte tid till det. <BR><BR>Det var roligt att få göra och det var verkligen fantastiskt att jag fick chansen att verkligen lära mig alla delar som man bara läser om eller ser bakom kulisserna.</span>',
      'textPin':'Casefilmer till Stadium Promotion.',
      'caseInputDate':'2016-08-17',
      'showArt':'0',
      'quote':null,
      'quoteName':'',
      'type':'Företagsfilmer',
      'colorSpace':'1',
      'employer':'2',
      'imgCollage':'4',
      'imgCollageSetup':'117,114,115,116',
      'tools':'1,2,3,5,6,12,13,15,18',
      'tasks':'29,28,1,2,3,4,10,11,12,13,14,16,20,21,22,23,24',
      'format':'MPEG-4H.264',
      'year':'2012',
      'link':null,
      'linkName':null,
      'imgThumb':'https://raw.githubusercontent.com/steffodimfelt/steffodimfelt.github.io/master/static/img/cases/film/2x1-SP-Case-03.jpg'
    },
    {
      'id':'27',
      'show':'1',
      'headline':'Svenska Spel, Kylskåpsmagnet',
      'textShort':'Kylskåpsmagnet för Trisslotter.',
      'textLong':'<span class=\'CapUp\'>Vissa saker ska man vara rädd om.<span> <span class="CapDown">Att tappa bort en miljon kan svida. Bäst att ta hand om den där Trisslotten. Den innehåller ju en dröm från vardagens sås och potatis. Och var passar inte bättre att drömma sig bort från mellanmjölken, än på utsidan på ett kylskåp?<BR><BR>Till Svenska Spels Triss gjorde jag originalet till en magnet med en ficka avsedd för en Trisslott. Självklart är det det en lotten med miljonvinst som ska sitta där och hägra.   <BR><BR>För plötsligt händer det...</span>',
      'textPin':'Kylskåpsmagnet för Trisslotter.',
      'caseInputDate':'2015-06-08',
      'showArt':'0',
      'quote':null,
      'quoteName':'',
      'type':'Kylskåpsmagnet',
      'colorSpace':'2',
      'employer':'2',
      'imgCollage':'3',
      'imgCollageSetup':'103,104,105',
      'tools':'2',
      'tasks':'9,27',
      'format':'Bredd: 68mm<BR>Höjd: 95mm',
      'year':'2008',
      'link':null,
      'linkName':null,
      'imgThumb':'https://raw.githubusercontent.com/steffodimfelt/steffodimfelt.github.io/master/static/img/cases/print/2x1-SvS-Magnet02.jpg'
    },
    {
      'id':'28',
      'show':'1',
      'headline':'Pontus Olgrim, Portfolio 2015',
      'textShort':'Personlig webbsida till Pontus Olgim.',
      'textLong':'<span class=\'CapUp\'>När skådespelaren Pontus Olgrim<span> <span class="CapDown">behövde en ny webbsida, skickade han ett sms med frågan till mig. Det är egentligen inte så konstigt, han är min gode vän och jag gjorde hans webbsida redan 2010. <BR><BR>Den nya sidan gjordes responsiv med allt innehåll på en sida istället för uppdelat på flera. <BR><BR>Det stora jobbet gjordes bakom kulisserna. Pontus vill själv kunna uppdatera allt på sidan när något nytt händer. <BR><BR>Min lösning blev en admin-del där Pontus exempelvis kan lägga upp nya jobb, ändra i alla texter, ladda upp nya bilder och ändra visningsläge för alla typeer av bilder på sidan.<BR><BR><strong>Det ska tilläggas att det 2016 gjordes en uppdatering av sidan, baserat på mitt wireframe-tools <a href=\'https://codepen.io/steffodimfelt/\'>Sluggo Beat Experience<a>.<strong></span>',
      'textPin':'Personlig webbsida till Pontus Olgim.',
      'caseInputDate':'2015-09-17',
      'showArt':'0',
      'quote':null,
      'quoteName':'',
      'type':'Webbsida',
      'colorSpace':'1',
      'employer':'9',
      'imgCollage':'2',
      'imgCollageSetup':'106,107',
      'tools':'25,19,11,24,8,9,1',
      'tasks':'28,7,8',
      'format':'Webbsida',
      'year':'2015',
      'link':'http//:pontusolgrim.se',
      'linkName':'pontusolgrim.se',
      'imgThumb':'https://raw.githubusercontent.com/steffodimfelt/steffodimfelt.github.io/master/static/img/cases/web/2X1-Pontus-Portfolio-2015-03.jpg'
    },
    {
      'id':'29',
      'show':'1',
      'headline':'\u00d6ppet Spår, Elverket, Dramaten',
      'textShort':'Två pjäser till \u00d6ppet Spår 2008 på Elverket.',
      'textLong':'<span class=\'CapUp\'>Regissören Mikael Berg<span> <span class="CapDown">tog 2008 initiativet till \u00d6ppet Spår.  Två måndagskvällar på Elverket veks till ett antal enaktare och monologer, som tillsammans blev en helkväll på två timmmar. <BR><BR>Mitt bidrag Parmiddagen, är en knapp halvtimmes färd från en trevlig parmiddag med karaoke, till ett nattsvart slut. Stor dos musik (alla medverkande hade sina musik-stundet) och lika stort dos med igenkänningsfaktorer. <BR><BR>Jag regisserade själv och var grymt nervös för den stundande premiären.<BR><BR>Jag blev uppringd  av Pontus Olgrim, som också ville vara med. Jag hade fullängdspjäs som hette Narcissus och den bantade jag ner till tio minuter och gjorde om den till ett kammarspel för två. Pontus spelade Narcissus och Anders Menzinsky spelade Brodern. <BR><BR>Pontus och jag gjorde senare en kortfilm av Narcissus<BR><BR>Nu var jag dubbelt så nervös, med två bidrag på samma gång, men det gick över förväntan. Det var jättekul att få publiken att skratta och förfäras.</span>',
      'textPin':'Två pjäser till \u00d6ppet Spår 2008 på Elverket.',
      'caseInputDate':'2015-09-27',
      'showArt':'0',
      'quote':null,'quoteName':'',
      'type':'Pjäser',
      'colorSpace':'6',
      'employer':'1',
      'imgCollage':'4',
      'imgCollageSetup':'109,110,111,112',
      'tools':'15',
      'tasks':'1,2',
      'format':'Pjäser',
      'year':'2008',
      'link':null,
      'linkName':null,
      'imgThumb':'https://raw.githubusercontent.com/steffodimfelt/steffodimfelt.github.io/master/static/img/cases/other/2x1-Par-Nar-2008-02.jpg'
    },
    {
      'id':'30',
      'show':'1',
      'headline':'Baktorget, Stockholmsmässan',
      'textShort':'En 3D-modellerad mössa till Bak&Choklad-mässan 2016.',
      'textLong':'<span class=\'CapUp\'>En av de mest besökta delarna av mässan Bak&Choklad<span> <span class="CapDown">var Baktorget - där medlemmar till branschorganisationen Sveriges bagare & konditorer stod och bakade under mässan. <BR><BR>Designavdelningen på Stockholmsmässan hade jobbat fram montern och en av tankarna var att en konditormössa med SBKs logotype skulle blir kronan på verket. En riktig konditormössa var beställd och skulle fotas, men den dök inte upp och tiden var knapp. Att producera en fyra meter lång cirkelvepa tar tid. <BR><BR>Min lösning blev att istället modellera upp en konditormössa i 3D. I underlaget från Designavdelningen fanns ett lågupplöst foto på en mössa som jag använde som referens. Jag ville komma så nära den bilden som möjligt. <BR><BR>Det tog knappt tre timmar att modellera upp mössan, plus tre timmar att sätta rätt struktur och ljus. Eftersom bilden behövde vara stor var jag lite orolig för renderinstiden. Som tur var hade jag lite hjälp av en renderingsfarm allt som allt (med slutfix i Photoshop och slutmontering till tryckfärdigt original), tog det ca 8 timmar.<BR><BR>Jag fick stor uppskattning för slutresultatet. På Stockholmsmässans Designavdelning sa de att bilden gav en illusion av en riktig mössa.</span>',
      'textPin':'En 3D-modellerad mössa till Bak&Choklad-mässan 2016.',
      'caseInputDate':'2016-10-15',
      'showArt':'1',
      'quote':'',
      'quoteName':'',
      'type':'3D-modell',
      'colorSpace':'2',
      'employer':'10',
      'imgCollage':'8',
      'imgCollageSetup':'120,119,121,118',
      'tools':'4,1,3 ',
      'tasks':'10,13,15,16',
      'format':'Cirkelvepa<BR>Bredd: 12540mm<BR>Höjd: 1500mm<BR><BR>Diskfront<BR>Bredd: 2020mm<BR>Höjd: 920mm',
      'year':'2016',
      'link':'',
      'linkName':'',
      'imgThumb':'https://raw.githubusercontent.com/steffodimfelt/steffodimfelt.github.io/master/static/img/cases/3d/BoC-01.jpg'
    },
    {
      'id':'31',
      'show':'1',
      'headline':'Editors\' Choice Award, Stockholmsmässan',
      'textShort':'Design av logotype, emblem och diplom till Editors\' Choice Award.',
      'textLong':'<span class=\'CapUp\'>Jag fick äran och möjligheten<span> <span class="CapDown">att designa logotype, emblem och diplom till Editors\' Choice Award. Presigepriset delas ut under Stockholm Furniture & Light Fair i kategorierna Rising Star, Best Stand och Best Product. Juryn består av chefredaktörer från några av Europas viktigaste designforum. <BR><BR>  <BR>Logotypeen tar avstamp från vinnarstatyetten som är formgiven av den svenska designern Lisa Hilland. Den består av tre kuber i olika storlekar, där en av sidorna på varje kub är en spegel. <BR><BR>  <BR>Man ville ha en modern, luftig och handritad känsla. Jag jobbade igenom logotypeen i tre steg: <BR><BR>1) Jag började med att ta fram tre moodboards som var och en gav en känsla av design och modernt formspråk. Jag satt med de ansvariga för ECA och diskuterade id\u00e9er, tankar och mål.<BR><BR>2) Utifrån diskussionerna skissade jag upp ett antal utkast som skickades fram och tillbaka några gånger för justeringar och input. <BR>3) En slutversion togs fram och färgsattes i en mörk grön färg som används i manualet till Furniture & Light Fair. Tanken var att färgen ändras från år till år.<BR><BR>4) Ett positivt och ett negativt grönt och vitt emblem togs fram. Dessutom gjorde jag även svartvita varianter. De olika emblemen är tänkta att att användas på olika medier - exempelvis är vita kuber på grön bakgrund tänkt att användas i sociala medier på nätet. <BR><BR>5) Slutligen tog jag fram diplomet, där kukberna gjordes i guldvinyl som monterades för hand innan de ramades in. Juryn fick skriva sin namnteckningar. <BR><BR>Det blev lite pill, men hela projektet gick förvånansvärt smidigt. Jag är väldigt stolt över slutresultatet och jag vet att de ansvariga blev mycket nöjda.</span>',
      'textPin':'Design av logotype, emblem och diplom till Editors\' Choice Award.',
      'caseInputDate':'2017-03-08',
      'showArt':'1',
      'quote':null,
      'quoteName':'',
      'type':'Logotype, emblem och diplom',
      'colorSpace':'5',
      'employer':'10',
      'imgCollage':'5',
      'imgCollageSetup':'122,123,124,125,126',
      'tools':'2,4',
      'tasks':'28,26,25',
      'format':'Diplom: A3-storlek<BR>Logotypeer i varierande storlek. ',
      'year':'2017',
      'link':'http//:www.stockholmfurniturelightfair.sevara-utstallningar-pa-stockholm-furniture---light-faireditors-choice-starteditors-choice-2017',
      'linkName':'Editors\' Choice Award 2017',
      'imgThumb':'https://raw.githubusercontent.com/steffodimfelt/steffodimfelt.github.io/master/static/img/cases/other/ECA-02.jpg'
    }
  ];
};